modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="BSD (3 clause)"

[[mods]] #mandatory
modId="slimemerger" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Slime Merger" #mandatory
description='''
Allows slimes to get together and make a bigger slime... occasionally.
'''

[[dependencies.slimemerger]] #optional
    modId="neoforge" #mandatory
    type="required"
    versionRange="[20.4.16-beta,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.slimemerger]]
    modId="minecraft"
type="required"
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"
