modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="BSD (3 clause)"

[[mods]] #mandatory
modId="slimemerger" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Slime Merger" #mandatory
description='''
Allows slimes to get together and make a bigger slime... occasionally.
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
