@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.slimemerger;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;